/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swisseph_SwephExp */

#ifndef _Included_swisseph_SwephExp
#define _Included_swisseph_SwephExp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     swisseph_SwephExp
 * Method:    swe_heliacal_ut
 * Signature: (D[D[D[DLjava/lang/String;II[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1heliacal_1ut
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jstring, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_heliacal_pheno_ut
 * Signature: (D[D[D[DLjava/lang/StringBuilder;II[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1heliacal_1pheno_1ut
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jstring, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_vis_limit_mag
 * Signature: (D[D[D[DLjava/lang/StringBuilder;I[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1vis_1limit_1mag
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jobject, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_heliacal_angle
 * Signature: (D[D[D[DIDDDDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1heliacal_1angle
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_topo_arcus_visionis
 * Signature: (D[D[D[DIDDDDDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1topo_1arcus_1visionis
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_set_astro_models
 * Signature: (Ljava/lang/StringBuilder;I)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1set_1astro_1models
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_astro_models
 * Signature: (Ljava/lang/StringBuilder;Ljava/lang/StringBuilder;I)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1get_1astro_1models
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_swisseph_SwephExp_swe_1version
  (JNIEnv *, jclass);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_library_path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_swisseph_SwephExp_swe_1get_1library_1path
  (JNIEnv *, jclass);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_calc
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1calc
  (JNIEnv *, jclass, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_calc_ut
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1calc_1ut
  (JNIEnv *, jclass, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_calc_pctr
 * Signature: (DIII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1calc_1pctr
  (JNIEnv *, jclass, jdouble, jint, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_fixstar
 * Signature: (Ljava/lang/StringBuilder;DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1fixstar
  (JNIEnv *, jclass, jobject, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_fixstar_ut
 * Signature: (Ljava/lang/StringBuilder;DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1fixstar_1ut
  (JNIEnv *, jclass, jobject, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_fixstar_mag
 * Signature: (Ljava/lang/StringBuilder;[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1fixstar_1mag
  (JNIEnv *, jclass, jobject, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_fixstar2
 * Signature: (Ljava/lang/StringBuilder;DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1fixstar2
  (JNIEnv *, jclass, jobject, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_fixstar2_ut
 * Signature: (Ljava/lang/StringBuilder;DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1fixstar2_1ut
  (JNIEnv *, jclass, jobject, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_fixstar2_mag
 * Signature: (Ljava/lang/StringBuilder;[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1fixstar2_1mag
  (JNIEnv *, jclass, jobject, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1close
  (JNIEnv *, jclass);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_set_ephe_path
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1set_1ephe_1path
  (JNIEnv *, jclass, jstring);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_set_jpl_file
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1set_1jpl_1file
  (JNIEnv *, jclass, jstring);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_planet_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_swisseph_SwephExp_swe_1get_1planet_1name
  (JNIEnv *, jclass, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_set_topo
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1set_1topo
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_set_sid_mode
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1set_1sid_1mode
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_ayanamsa_ex
 * Signature: (DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1get_1ayanamsa_1ex
  (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_ayanamsa_ex_ut
 * Signature: (DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1get_1ayanamsa_1ex_1ut
  (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_ayanamsa
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1get_1ayanamsa
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_ayanamsa_ut
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1get_1ayanamsa_1ut
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_ayanamsa_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_swisseph_SwephExp_swe_1get_1ayanamsa_1name
  (JNIEnv *, jclass, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_current_file_data
 * Signature: (I[D[D[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_swisseph_SwephExp_swe_1get_1current_1file_1data
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jintArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_date_conversion
 * Signature: (IIIDC[D)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1date_1conversion
  (JNIEnv *, jclass, jint, jint, jint, jdouble, jchar, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_julday
 * Signature: (IIIDI)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1julday
  (JNIEnv *, jclass, jint, jint, jint, jdouble, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_revjul
 * Signature: (DI[I[D)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1revjul
  (JNIEnv *, jclass, jdouble, jint, jintArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_utc_to_jd
 * Signature: (IIIIIDI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1utc_1to_1jd
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_jdet_to_utc
 * Signature: (DI[I[D)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1jdet_1to_1utc
  (JNIEnv *, jclass, jdouble, jint, jintArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_jdut1_to_utc
 * Signature: (DI[I[D)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1jdut1_1to_1utc
  (JNIEnv *, jclass, jdouble, jint, jintArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_utc_time_zone
 * Signature: (IIIIIDD[I[D)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1utc_1time_1zone
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jdouble, jdouble, jintArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_houses
 * Signature: (DDDI[D[D)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1houses
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_houses_ex
 * Signature: (DIDDI[D[D)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1houses_1ex
  (JNIEnv *, jclass, jdouble, jint, jdouble, jdouble, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_houses_ex2
 * Signature: (DIDDI[D[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1houses_1ex2
  (JNIEnv *, jclass, jdouble, jint, jdouble, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_houses_armc
 * Signature: (DDDI[D[D)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1houses_1armc
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_houses_armc_ex2
 * Signature: (DDDI[D[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1houses_1armc_1ex2
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_house_pos
 * Signature: (DDDI[DLjava/lang/StringBuilder;)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1house_1pos
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_house_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_swisseph_SwephExp_swe_1house_1name
  (JNIEnv *, jclass, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_gauquelin_sector
 * Signature: (DILjava/lang/StringBuilder;II[DDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1gauquelin_1sector
  (JNIEnv *, jclass, jdouble, jint, jobject, jint, jint, jdoubleArray, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_sol_eclipse_where
 * Signature: (DI[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1sol_1eclipse_1where
  (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_lun_occult_where
 * Signature: (DILjava/lang/StringBuilder;I[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1lun_1occult_1where
  (JNIEnv *, jclass, jdouble, jint, jobject, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_sol_eclipse_how
 * Signature: (DI[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1sol_1eclipse_1how
  (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_sol_eclipse_when_loc
 * Signature: (DI[D[D[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1sol_1eclipse_1when_1loc
  (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_lun_occult_when_loc
 * Signature: (DILjava/lang/StringBuilder;I[D[D[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1lun_1occult_1when_1loc
  (JNIEnv *, jclass, jdouble, jint, jobject, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_sol_eclipse_when_glob
 * Signature: (DII[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1sol_1eclipse_1when_1glob
  (JNIEnv *, jclass, jdouble, jint, jint, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_lun_occult_when_glob
 * Signature: (DILjava/lang/StringBuilder;II[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1lun_1occult_1when_1glob
  (JNIEnv *, jclass, jdouble, jint, jobject, jint, jint, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_lun_eclipse_how
 * Signature: (DI[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1lun_1eclipse_1how
  (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_lun_eclipse_when
 * Signature: (DII[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1lun_1eclipse_1when
  (JNIEnv *, jclass, jdouble, jint, jint, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_lun_eclipse_when_loc
 * Signature: (DI[D[D[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1lun_1eclipse_1when_1loc
  (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_pheno
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1pheno
  (JNIEnv *, jclass, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_pheno_ut
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1pheno_1ut
  (JNIEnv *, jclass, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_refrac
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1refrac
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_refrac_extended
 * Signature: (DDDDDI[D)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1refrac_1extended
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_set_lapse_rate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1set_1lapse_1rate
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_azalt
 * Signature: (DI[DDD[D[D)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1azalt
  (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jdouble, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_azalt_rev
 * Signature: (DI[D[D[D)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1azalt_1rev
  (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_rise_trans_true_hor
 * Signature: (DILjava/lang/StringBuilder;II[DDDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1rise_1trans_1true_1hor
  (JNIEnv *, jclass, jdouble, jint, jobject, jint, jint, jdoubleArray, jdouble, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_rise_trans
 * Signature: (DILjava/lang/StringBuilder;II[DDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1rise_1trans
  (JNIEnv *, jclass, jdouble, jint, jobject, jint, jint, jdoubleArray, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_nod_aps
 * Signature: (DIII[D[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1nod_1aps
  (JNIEnv *, jclass, jdouble, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_nod_aps_ut
 * Signature: (DIII[D[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1nod_1aps_1ut
  (JNIEnv *, jclass, jdouble, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_orbital_elements
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1get_1orbital_1elements
  (JNIEnv *, jclass, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_orbit_max_min_true_distance
 * Signature: (DII[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1orbit_1max_1min_1true_1distance
  (JNIEnv *, jclass, jdouble, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_deltat
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1deltat
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_deltat_ex
 * Signature: (DILjava/lang/StringBuilder;)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1deltat_1ex
  (JNIEnv *, jclass, jdouble, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_time_equ
 * Signature: (D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1time_1equ
  (JNIEnv *, jclass, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_lmt_to_lat
 * Signature: (DD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1lmt_1to_1lat
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_lat_to_lmt
 * Signature: (DD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1lat_1to_1lmt
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_sidtime0
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1sidtime0
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_sidtime
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1sidtime
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_set_interpolate_nut
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1set_1interpolate_1nut
  (JNIEnv *, jclass, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_cotrans
 * Signature: ([D[DD)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1cotrans
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_cotrans_sp
 * Signature: ([D[DD)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1cotrans_1sp
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_get_tid_acc
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1get_1tid_1acc
  (JNIEnv *, jclass);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_set_tid_acc
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1set_1tid_1acc
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_set_delta_t_userdef
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1set_1delta_1t_1userdef
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_degnorm
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1degnorm
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_radnorm
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1radnorm
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_rad_midp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1rad_1midp
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_deg_midp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1deg_1midp
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_split_deg
 * Signature: (DI[I[D[I)V
 */
JNIEXPORT void JNICALL Java_swisseph_SwephExp_swe_1split_1deg
  (JNIEnv *, jclass, jdouble, jint, jintArray, jdoubleArray, jintArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_solcross
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1solcross
    (JNIEnv *, jclass, jdouble, jdouble, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_solcross_ut
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1solcross_1ut
    (JNIEnv *, jclass, jdouble, jdouble, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_mooncross
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1mooncross
    (JNIEnv *, jclass, jdouble, jdouble, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_mooncross_ut
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1mooncross_1ut
    (JNIEnv *, jclass, jdouble, jdouble, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_mooncross_node
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1mooncross_1node
    (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_mooncross_node_ut
 */
JNIEXPORT jdouble JNICALL Java_swisseph_SwephExp_swe_1mooncross_1node_1ut
    (JNIEnv *, jclass, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_helio_cross
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1helio_1cross
    (JNIEnv *, jclass, jint, jdouble, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    swe_helio_cross_ut
 */
JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1helio_1cross_1ut
    (JNIEnv *, jclass, jint, jdouble, jdouble, jint, jint, jdoubleArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
